#端口
server: 
  port: 8999
  tomcat: 
    uri-encoding: UTF-8
spring:
#  application:
#    name: client
  thymeleaf:
      prefix: classpath:/templates
      encoding: UTF-8
  #缓存
      cache: false
#表示所有的访问都经过静态资源路径；
  mvc:
    static-path-pattern: /**
#在这里配置静态资源路径，前面说了这里的配置是覆盖默认配置，
#所以需要将默认的也加上否则static、public等这些路径将不能被当作静态资源路径，
#在这个最末尾的file:${web.upload-path}之所有要加file:是因为指定的是一个具体的硬盘路径，
#其他的使用classpath指的是系统环境变量
  resources:
    static-locations: classpath:/static/,classpath:/public/,file:${filesPath}

#database
  datasource:
    url: jdbc:sqlserver://192.168.1.249:1433;DatabaseName=watch
    username: watch
    password: watch
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#  jpa.properties.hibernate.default_schema = schema

  output:
      ansi:
        enabled: ALWAYS

# 日志级别
info: true
logging:
    file: watch.log
    level:
      org:
        watch:
          com: debug

#分页每页默认条数设置
page:
  pageSize: 10

pagehelper:
    helperDialect: sqlserver
    reasonable: true
    supportMethodsArguments: true
    params:
        count:
            countSql

#全局上传下载读取文件路径设置
filesPath: D:\\file\\
#全局文件格式-多个用,(英文)隔开
filesType: xlsx